### ISSUE TITLE
Need Support for Mavic Air 2

### ISSUE THREAD

**Issue by alzin** [dji-sdk/Mobile-UXSDK-iOS#102]
I got my new Mavic Air 2 drone and tested it already on DJI Fly App with the provided simulator and everything went well.
After that, I tried hard to make the new SDK 4.14 work with an App I am developing but I couldn't do anything. Even tried with the provided code from DJI also not able to make it work. I feel that working with Mavic Air 2 nowadays still with poor documentation because it says that the new SDK release supports it but it seems there are a lot of bugs or so whatever!!

Any help Please??

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49722'>Zendesk ticket #49722</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Yes, the UXSDK 4.14 has supported the Mavic Air 2.
Can you please test it again with the official UXSDK sample?
https://github.com/dji-sdk/Mobile-UXSDK-iOS
 ![](https://djisdksupport.zendesk.com/attachments/token/p6UA1POlWHR2bRQ5wserghxaT/?name=inline-665143538.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/p6UA1POlWHR2bRQ5wserghxaT' target='zd_attach'>inline-665143538.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by vitansoz** [comment]
I have same problems,no Real-time picture display

DJI-SDK-iOS (4.14)
DJI-UXSDK-iOS (4.14)
DJIWidget (1.6.3)

![63200330-9793-4D74-8899-52CA54D5EFDD](https://user-images.githubusercontent.com/45025677/128446249-88a154e0-92d5-4386-b103-c6c8a151f4de.jpeg)

**Comment by alzin** [comment]
@vitansoz 

Consider using the beta version of the UX SDK that supports Mavic Air 2 and all versions as well!
let me know if you need any help after trying using it!

[https://github.com/dji-sdk/Mobile-UXSDK-Beta-iOS](url)
