### ISSUE TITLE
Menu button is now gone with version 4.3

### ISSUE THREAD

**Issue by Daxito** [dji-sdk/Mobile-UXSDK-iOS#13]
Hi,
In version 4.2 we used to have a Menu button that would allow us to format the SD Card and other things, now it is gone, how can I show it again?

![20170922_102728](https://user-images.githubusercontent.com/16787057/30752873-4627bbca-9f83-11e7-9b47-270f8b5468ef.jpg)

Thanks

**Comment by Daxito** [comment]
Update: The button seems like is is there, but it cannot be seen from the iPhone 5, if you use a bigger phone like an iPhone 6, then you can see the Menu button

**Comment by Daxito** [comment]
Is there any suggestion for this issue? I still cannot see the button in version 4.4 of the UI library

**Comment by zoemcateedji** [comment]
Tablets and large phones are the target devices for the UILibrary, so as a work around for the iPhone 5 you could hide "trailingviewcontroller" in the default layout, and then individually place the widgets.

**Comment by Daxito** [comment]
Thank you @zoemcateedji , I will take a look at that then, also good to know the ideal target of this Library.

**Comment by Daxito** [comment]
@zoemcateedji , How can I add the widget DULCameraSettingsMenu to the UI? I added it to a View but it displays nothing in it, is there a special way? I can add other Widgets but not this one, no error no nothing, just display empty view.

**Comment by Daxito** [comment]
So I was able to make it display the "menu" word, but when I tap on it it does nothing, my view has "user interaction enabled", do you think I am still missing something?
