### ISSUE TITLE
Invalid `Podfile` file: syntax error, unexpected << (aka merge with issues)

### ISSUE THREAD

**Issue by vvahans** [dji-sdk/Mobile-UXSDK-iOS#74]
After  [this](https://github.com/dji-sdk/Mobile-UXSDK-iOS/commit/b23548a22480ac218a6cfd8f89e311cf9c366032#diff-3568cb5f7348581b6cf9c4213dcd002d) merge
`pod install` in `Mobile-UXSDK-iOS/Sample Code/SwiftSampleCode` fails with 

> [!] Invalid `Podfile` file: syntax error, unexpected <<, expecting end
> <<<<<<< HEAD
> ^~
> /Mobile-UXSDK-iOS/Sample Code/SwiftSampleCode/Podfile:11: syntax error, unexpected end, expecting end-of-input.
> 
>  #  from /Mobile-UXSDK-iOS/Sample Code/SwiftSampleCode/Podfile:5
>  #  -------------------------------------------
>  #    use_frameworks!
>  >  <<<<<<< HEAD
>  #    pod 'DJI-SDK-iOS', '~> 4.11.1'
>  #  -------------------------------------------

File to fix: [https://github.com/dji-sdk/Mobile-UXSDK-iOS/blob/master/Sample%20Code/SwiftSampleCode/Podfile](https://github.com/dji-sdk/Mobile-UXSDK-iOS/blob/master/Sample%20Code/SwiftSampleCode/Podfile)

**Comment by dji-dev** [comment]
Public comment from Lisa Fedane in <a href='https://djisdksupport.zendesk.com/agent/tickets/31951'>Zendesk ticket #31951</a>:<br><br>Thanks for bringing this to our attention - I am escalated this to our engineers now.


Lisa Fedane
DJI Developer Support

**Comment by dji-dev** [comment]
Agent comment from Hummels Lei in <a href='https://djisdksupport.zendesk.com/agent/tickets/31951'>Zendesk ticket #31951</a>:<br><br>Hi. I want to know if the problem in this ticket has been solved.
For now, we have released the latest 4.14 iOS SDK, you can upgrade to the latest SDK to test again.
If the problem persists, please post it on our new forum https://djisdksupport.zendesk.com/hc/en-us/community/topics. We will solve it for you through the forum.
<br><p><em><small>°°°</small></em></p>
